require:
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.6
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'
    - !ruby/regexp /old_and_unused\.rb$/

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'