name: Ruby
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        ruby_version: [2.5, 2.6]
    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby ${{ matrix.ruby_version }}
      uses: actions/setup-ruby@v1
      with:
        version: ${{ matrix.ruby_version }}
    - name: Build and test
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rspec --format progress --format RspecJunitFormatter
